package modelo;
// Generated 23/04/2016 12:26:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idAlumno;
     private String ANombre;
     private String AContrasenha;
     private String ACorreo;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Alumno() {
    }

	
    public Alumno(int idAlumno, String AContrasenha, String ACorreo) {
        this.idAlumno = idAlumno;
        this.AContrasenha = AContrasenha;
        this.ACorreo = ACorreo;
    }
    public Alumno(int idAlumno, String ANombre, String AContrasenha, String ACorreo, Set<Solicitud> solicituds) {
       this.idAlumno = idAlumno;
       this.ANombre = ANombre;
       this.AContrasenha = AContrasenha;
       this.ACorreo = ACorreo;
       this.solicituds = solicituds;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getANombre() {
        return this.ANombre;
    }
    
    public void setANombre(String ANombre) {
        this.ANombre = ANombre;
    }
    public String getAContrasenha() {
        return this.AContrasenha;
    }
    
    public void setAContrasenha(String AContrasenha) {
        this.AContrasenha = AContrasenha;
    }
    public String getACorreo() {
        return this.ACorreo;
    }
    
    public void setACorreo(String ACorreo) {
        this.ACorreo = ACorreo;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


