package modelo;
// Generated 23/04/2016 12:26:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int idArea;
     private String AArea;
     private Set<Actividad> actividads = new HashSet<Actividad>(0);

    public Area() {
    }

	
    public Area(int idArea) {
        this.idArea = idArea;
    }
    public Area(int idArea, String AArea, Set<Actividad> actividads) {
       this.idArea = idArea;
       this.AArea = AArea;
       this.actividads = actividads;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public String getAArea() {
        return this.AArea;
    }
    
    public void setAArea(String AArea) {
        this.AArea = AArea;
    }
    public Set<Actividad> getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set<Actividad> actividads) {
        this.actividads = actividads;
    }




}


