package modelo;
// Generated 23/04/2016 12:26:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private int idProfesor;
     private String PNombre;
     private String PContrasenha;
     private String PCorreo;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<Actividad> actividads = new HashSet<Actividad>(0);

    public Profesor() {
    }

	
    public Profesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Profesor(int idProfesor, String PNombre, String PContrasenha, String PCorreo, Set<Solicitud> solicituds, Set<Actividad> actividads) {
       this.idProfesor = idProfesor;
       this.PNombre = PNombre;
       this.PContrasenha = PContrasenha;
       this.PCorreo = PCorreo;
       this.solicituds = solicituds;
       this.actividads = actividads;
    }
   
    public int getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }
    public String getPNombre() {
        return this.PNombre;
    }
    
    public void setPNombre(String PNombre) {
        this.PNombre = PNombre;
    }
    public String getPContrasenha() {
        return this.PContrasenha;
    }
    
    public void setPContrasenha(String PContrasenha) {
        this.PContrasenha = PContrasenha;
    }
    public String getPCorreo() {
        return this.PCorreo;
    }
    
    public void setPCorreo(String PCorreo) {
        this.PCorreo = PCorreo;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<Actividad> getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set<Actividad> actividads) {
        this.actividads = actividads;
    }




}


