package modelo;
// Generated 23/04/2016 12:26:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private int idTipo;
     private String ATipo;
     private Set<Actividad> actividads = new HashSet<Actividad>(0);

    public Tipo() {
    }

	
    public Tipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public Tipo(int idTipo, String ATipo, Set<Actividad> actividads) {
       this.idTipo = idTipo;
       this.ATipo = ATipo;
       this.actividads = actividads;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getATipo() {
        return this.ATipo;
    }
    
    public void setATipo(String ATipo) {
        this.ATipo = ATipo;
    }
    public Set<Actividad> getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set<Actividad> actividads) {
        this.actividads = actividads;
    }




}


